In [18]:
#ONE DIMENSTIONAL ARRAY

In [22]:
import numpy as np
list1=[1,2,3,4]
arr1=np.array(list1)
print(arr1)
print(arr1.ndim)

[1 2 3 4]
1


In [4]:
list1=[1,2,3,4]


[2 4 6 8]


In [5]:
print(list1*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [6]:
type(arr1)

numpy.ndarray

In [20]:
arr2=np.array([10,20,30,40])
print(arr2)
arr2.shape

[10 20 30 40]


(4,)

In [ ]:
#TWO DIMENSIONAL ARRAY

In [23]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr3)
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
12
(4, 3)


In [9]:
arr4=np.array([[12,13,14],[14,15,16]])
print(arr4)
print(arr4.size)

[[12 13 14]
 [14 15 16]]
6


In [ ]:
#THREE DIMENSIONAL ARRAY

In [14]:
arr5=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,15,20],[30,40,50],[60,70,80]],[[34,56,78],[18,19,20],[22,33,44]]])
print(arr5)
print(arr5.ndim)
print(arr5.size)
print(arr5.shape)



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 15 20]
  [30 40 50]
  [60 70 80]]

 [[34 56 78]
  [18 19 20]
  [22 33 44]]]
3
27
(3, 3, 3)


In [19]:
#RESHAPE AN ARRAY

In [24]:
#1D TO 2D ARRAY

In [26]:
arr6=arr1.reshape(2,2)
print(arr6)

[[1 2]
 [3 4]]


In [ ]:
#1D TO 3D ARRAY

In [31]:
arr7=np.array([1,2,3,4,5,6,7,8])
arr8=arr7.reshape(2,2,2)
print(arr8)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#2D TO 3D ARRAY

In [34]:
arr8=np.array([[1,2],[3,4],[5,6],[6,7]])
arr9=arr8.reshape(2,2,2)
print(arr9)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [ ]:
#2D TO 2D ARRAY

In [37]:
arr10=arr8.reshape(2,4)
print(arr10)

[[1 2 3 4]
 [5 6 6 7]]


In [ ]:
#3D TO 3D ARRAY

In [41]:
arr11=arr5.reshape(1,9,3)
print(arr11)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 15 20]
  [30 40 50]
  [60 70 80]
  [34 56 78]
  [18 19 20]
  [22 33 44]]]


In [42]:
arr12=arr4.reshape(-1)
print(arr12)

[12 13 14 14 15 16]


In [ ]:
#FIND DATA TYPES OF AN ARRAY

In [3]:
import numpy as np
arr13=np.array([1,2,3,4,5,])
print(arr13.dtype)
arr14=np.array([1.2,2.2,3.3,4.4])
print(arr14.dtype)
arr15=np.array(['a','b','c','d','e'])
print(arr15.dtype)

int32
float64
<U1


In [ ]:
#CREATE AN ARRAY WITH SPECIFIC OF DATATYPE

In [5]:
import numpy as np
arr16=np.array([1,2,3,4,5],dtype=np.float16)
print(arr16)
print(arr16.dtype)

[1. 2. 3. 4. 5.]
float16


In [8]:
import numpy as np
arr17=np.array([1.1,2.2,3.3,4.4,5.5],dtype=np.int32)
print(arr17)
print(arr17.dtype)

[1 2 3 4 5]
int32


In [ ]:
#HOW TO CONVERT AN ARRAY TO ANOTHER DATATYPE

In [15]:
import numpy as np
arr18=np.array([1,2,3,4,5],dtype=np.int8)
arr19=arr18.astype(np.float16)
print(arr19)
print(arr19.dtype)

[1. 2. 3. 4. 5.]
float16


In [ ]:
#ARRAY CREATION METHOD

In [ ]:
#numpy.array()

In [17]:
arr20=np.array([1,2,3,4])
print(arr20)

[1 2 3 4]


In [ ]:
#NUMPY.ZEROS()

In [19]:
arr21=np.zeros(6)
print(arr21)

[0. 0. 0. 0. 0. 0.]


In [21]:
arr22=np.zeros((4,4))
print(arr22)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
arr23=np.zeros(((2,4,4)))
print(arr23)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#numpy.ones()

In [26]:
arr24=np.ones((2,4,4))
print(arr24)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
#numpy.arange()

In [31]:
arr25=np.arange(10)
print(arr25)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
arr26=np.arange(1,11)
print(arr26)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
arr27=np.arange(10,27)
print(arr27)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]


In [35]:
arr28=np.arange(10,29,2)
print(arr28)

[10 12 14 16 18 20 22 24 26 28]


In [ ]:
#numpy.linspace()

In [36]:
arr29=np.linspace(1,10,5)
print(arr29)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#numpy.eye()

In [37]:
arr30=np.eye(4)
print(arr30)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
arr31=np.eye(6,4)
print(arr31)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
arr32=np.eye(6,4,1)
print(arr32)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
arr33=np.eye(6,4,2)
print(arr33)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
arr34=np.eye(6,4,-1)
print(arr34)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
#numpy.full()

In [43]:
arr35=np.full(5,12)
print(arr35)

[12 12 12 12 12]


In [45]:
arr36=np.full((3,5),13)
print(arr36)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [ ]:
#numpy.random.randint()


In [51]:
arr37=np.random.randint(0,11,(2,2))
print(arr37)

[[ 1 10]
 [ 8  9]]


In [53]:
arr38=np.random.randint(0,100,((2,2,2)))
print(arr38)

[[[63  9]
  [90 37]]

 [[79  7]
  [ 6 39]]]


In [ ]:
#numpy.random.random()

In [55]:
arr39=np.random.random(4)
print(arr39)

[0.18559159 0.73719787 0.49942327 0.3587865 ]


In [57]:
arr40=np.random.random((2,2))
print(arr40)

[[0.9634226  0.94778752]
 [0.66682234 0.62878752]]


In [ ]:
#TO FIND THE SUM

In [2]:
import numpy as np
arr41=np.random.randint(4,15,5)
sum=np.sum(arr41)
print(arr41)
print(sum)

[ 8  7  9 10  8]
42


import numpy as np
arr42=np.random.random(5)
sum=np.sum(arr42)
print(arr42)
print(sum)

In [ ]:
#MEAN,MEDIAN,Standard deviation

In [7]:
arr43=np.random.randint(1,100,10)
sum1=np.sum(arr43)
mean=np.mean(arr43)
median=np.median(arr43)
deviation=np.std(arr43)
print("ARRAY=",arr43)
print("SUM=",sum1)
print("MEAN=",mean)
print("MEADIAN=",median)
print("DEVIATION",deviation)

ARRAY= [74 73 53 47 75 81 36 54 38  2]
SUM= 533
MEAN= 53.3
MEADIAN= 53.5
DEVIATION 22.934907891683366


In [ ]:
#ARRAY INDEXING

In [ ]:
#ARRAY ACCESSING

In [15]:
arr44=np.arange(10,100,10)
arr44[-1]


90

In [16]:
arr44=np.arange(10,100,10)
arr44[0]

10

In [17]:
arr44=np.arange(10,100,10)
arr44[4]

50

In [24]:
arr45=np.array([[2,4,3],[3,5,8],[5,6,2]])
arr45[1,2]

8

In [27]:
arr46=np.array([[[0,1],[12,14]],[[12,14],[16,18]]])
arr46[1,1,1]

18

In [ ]:
#ARRAY SLICING

In [ ]:
#1D ARRAY SLICING

In [28]:
arr47=np.arange(10,100,10)
arr47[1:6]

array([20, 30, 40, 50, 60])

In [29]:
arr47=np.arange(10,100,10)
arr47[1:]

array([20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
arr47=np.arange(10,100,10)
arr47[:6]

array([10, 20, 30, 40, 50, 60])

In [ ]:
#NEGATIVE SLICING

In [33]:
arr48=np.arange(10,110,10)
arr48[-9:-3]

array([20, 30, 40, 50, 60, 70])

In [ ]:
#ARRAY SLICING WITH INTERVAL

In [35]:
arr48[::2]

array([10, 30, 50, 70, 90])

In [36]:
arr48[2:7:2]

array([30, 50, 70])

In [ ]:
#2D ARRAY SLICING 

In [37]:
arr49=np.array([[3,6,9],[12,15,18],[21,24,27]])
arr49[1,0:2]

array([12, 15])

In [38]:
arr49[1:3,0:2]

array([[12, 15],
       [21, 24]])

In [ ]:
#3D ARRAY SLICING   

In [41]:
arr46
arr46[1,1,0:2]

array([16, 18])

In [43]:
arr46
arr46[1,0:2,0:2]

array([[12, 14],
       [16, 18]])

In [ ]:
#NUMPY ARRAY TASKS 

In [ ]:
#1. Creating Arrays 

In [ ]:
#Task 1: Create a NumPy array with integers from 1 to 10. 

In [2]:
import numpy as np
arr47=np.arange(1,11,1)
print(arr47)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Task 2: Create a 2D array of size 3x3 with all elements equal to 7

In [4]:
arr48=np.full((3,3),7)
print(arr48)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#Task 3: Create an array of shape (5, 5) with random float values between 0 and 1. 

In [6]:
arr49=np.random.random((5,5))
print(arr49)

[[0.27275207 0.28035912 0.88560007 0.32305841 0.84175354]
 [0.66633444 0.11259448 0.10480612 0.45774671 0.68484628]
 [0.33734039 0.29195078 0.20122011 0.26664312 0.64030572]
 [0.76906845 0.07715206 0.61065641 0.76253308 0.83318118]
 [0.80818381 0.23664418 0.94840745 0.60631424 0.5623268 ]]


In [ ]:
# Task 4: Create a 1D array containing the first 10 square numbers (i.e., [1, 4, 9, 16, 25, ..., 100]).

In [9]:
arr50=np.arange(1,11,1)
square=list(map(lambda x:x**2,arr50))
print(square)            

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#2. Array Operations 

In [ ]:
# Task 5: Create two arrays of the same size and perform element-wise addition, subtraction, 
multiplication, and division.

In [14]:
arr51=np.array([1,2,4,5,3,6])
arr52=np.array([2,8,9,4,7,1])
add=arr51+arr52
sub=arr51-arr52
mul=arr51*arr52
div=arr51%arr52
print('add=',add)
print('sub=',sub)
print('mul=',mul)
print('div=',div)


add= [ 3 10 13  9 10  7]
sub= [-1 -6 -5  1 -4  5]
mul= [ 2 16 36 20 21  6]
div= [1 2 4 1 3 0]


In [ ]:
#Task 6: Find the dot product of two 2D arrays. 

In [21]:
arr53=np.array([[3,5],[6,9],[9,10]])
arr54=np.array([[2,9],[7,4],[8,11]])
dot1=np.dot(arr53,arr54.T)
print(dot1)

[[ 51  41  79]
 [ 93  78 147]
 [108 103 182]]


In [ ]:
#Task 7: Find the sum, mean, median, and standard deviation of a given array. 

In [23]:
arr55=np.array([3,5,7,9,8,6,4,10,2])
sum1=np.sum(arr55)
mean=np.mean(arr55)
std=np.std(arr55)
median=np.median(arr55)
print('sum=',sum1)
print('mean=',mean)
print('std=',std)
print('median=',median)

sum= 54
mean= 6.0
std= 2.581988897471611
median= 6.0


In [ ]:
# Array Indexing and Slicing 

In [ ]:
Task 8: Create a 2D array of shape (5, 5) with values from 1 to 25 and extract the subarray from 
the 2nd to 4th row and 2nd to 4th column. 

In [3]:
import numpy as np
arr56=np.arange(1,26,1)
arr57=arr56.reshape(5,5)
print(arr57)
arr58=arr57[1:4,1:4]
print(arr58)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
#Task 9: Use boolean indexing to replace all negative values in a NumPy array with zero. 

In [5]:
arr59=np.array([2,3,5,-9,-1,2,-7,10])
arr59[arr59<0]=0
print(arr59)

[ 2  3  5  0  0  2  0 10]


In [ ]:
#Task 10: Create an array and slice every alternate element (odd indices) from the original array. 

In [9]:
arr60=np.arange(5,56,5)
print(arr60)
arr61=arr60[1::2]
print(arr61)

[ 5 10 15 20 25 30 35 40 45 50 55]
[10 20 30 40 50]


In [ ]:
#4. Array Reshaping and Transposing

In [ ]:
#Task 11: Convert a 1D array of 12 elements into a 3x4 2D array.

In [12]:
arr62=np.random.randint(1,100,12)
print(arr62)
arr63=arr62.reshape((3,4))
print(arr63)

[62 93 39 50 66 89 77 69 34 56 42 18]
[[62 93 39 50]
 [66 89 77 69]
 [34 56 42 18]]


In [ ]:
#Task 12: Transpose a 2D array and find its shape

In [16]:
arr63=np.random.randint(2,60,(3,4))
print(arr63)
arr64=arr63.reshape(2,3,2)
print(arr64)
print(np.shape(arr63))
print(np.shape(arr64))

[[25  3  4 53]
 [44 53 18  5]
 [40 23 47 43]]
[[[25  3]
  [ 4 53]
  [44 53]]

 [[18  5]
  [40 23]
  [47 43]]]
(3, 4)
(2, 3, 2)


In [ ]:
# Task 13: Flatten a 3D array (e.g., of shape (2, 3, 4)) into a 1D array.

In [20]:
arr62=np.random.randint(1,100,12)
arr63=arr62.reshape(2,2,3)
print('3D array=',arr63)
arr64=arr63.reshape(12)
print('reshaped 1 D array=',arr64)

3D array= [[[85 80 12]
  [97 56 52]]

 [[36 60 24]
  [11 49 99]]]
reshaped 1 D array= [85 80 12 97 56 52 36 60 24 11 49 99]
